### ISSUE TITLE
Upgrade Geth: 1.8.27 > 1.9.5

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-les#1]
We're still running old geth on our LES fleet:
```
 $ ansible all -o -a "docker inspect les-geth-full -f '{%raw%}{{.Config.Image}}{%endraw%}'"

node-01.do-ams3.rops.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
node-02.do-ams3.rops.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
node-03.do-ams3.main.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
node-03.do-ams3.rops.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
node-02.do-ams3.main.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
node-01.do-ams3.main.les | CHANGED | rc=0 | (stdout) ethereum/client-go:v1.8.27
```
Will also have to look into syncing issues since that seems broken:
https://grafana.status.im/d/VyUgFRWZz/geth-syncing?orgId=1&var-fleet=main.les&from=now-90d&to=now

**Comment by jakubgs** [comment]
I have upgraded the Geth version in: 26c5a4e1b20d9b8376e3f51d55b5823be23c00e9
Also purged all the Geth data and let the hosts sync again from scratch:
https://grafana.status.im/d/VyUgFRWZz/geth-syncing?orgId=1&var-fleet=main.les&from=now-1h&to=now
And added @3esmit node via `static-nodes.json`:
```
enode://99b3c97867c5f051e92e0b07ba1529d10dee63999f40a1ee0f6720c5940792d90da352cc57c270207879298d08bc1575ffc0db5b795048125c7b46406e8545d8@186.226.150.180:30303
```
We'll see what happens.

**Comment by jakubgs** [comment]
Not syncing properly, I think the container is restarting due to memory limitations:
![fucked_up_sync](https://user-images.githubusercontent.com/2212681/65956463-bc565c80-e44a-11e9-83aa-1fa77b5b5985.png)

**Comment by jakubgs** [comment]
Yep, the container keeps hitting the memory limit:
![geth_mem_limit_hit](https://user-images.githubusercontent.com/2212681/65956928-d6dd0580-e44b-11e9-8155-e05916256345.png)

**Comment by jakubgs** [comment]
I let it run with new memory limits for a whole day but the syncing process is still all kinds of fucked up:
![fucked_up_sync_000](https://user-images.githubusercontent.com/2212681/66047456-1da02d80-e528-11e9-9a76-531e695ebbb3.png)
But memory usage is normal, no process restarts this time around:
![fucked_up_sync_mem_000](https://user-images.githubusercontent.com/2212681/66047564-41637380-e528-11e9-82ea-56a15160c277.png)
So I have no fucking clue why this trash software is not syncing.

**Comment by 3esmit** [comment]
In my computer in synced with no problems, at first try, it just taked from 09-21|10:16:49.961  to 09-26|04:06:11.915 . 

I have the full sync log if you want to see.

The behavior you noticing is it rolling back blocks because it started downloading a wrong thing. This happened on my sync aswell, but not much. 

After fast sync finishes downloading block headers it will download state entries, and you will not see any more reverts.

**Comment by jakubgs** [comment]
Okay, lets let it run, we'll see what it does in the long run.

**Comment by jakubgs** [comment]
This fleet is a waste of time and money, I've destroyed it for now: 47ee45872d193bd759f056f60e0c4b018dfe0ce7
Closing this, we can get back to this when we actually need those hosts.
